name: flutter_task_master
description: "A modern and minimalist task management app built with Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
  
dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_slidable: ^3.1.1
  
  # State Management
  provider: ^6.1.2
  
  # Local Storage
  shared_preferences: ^2.3.2
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/screenshots/
